name: Build and Deploy Windows Executable

on:
  push:
    branches:
      - main  # Adjust this based on your main branch name

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable
        run: pyinstaller --onefile --noconsole win_main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: dist/win_main.exe

  deploy:
    needs: build
    runs-on: ubuntu-latest  # Use a Linux runner for deployment

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: windows-executable

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0  # Replace with the desired tag name
          release_name: Release v1.0  # Customize release name
          draft: false
          prerelease: false

      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./win_main.exe
          asset_name: win_main.exe
          asset_content_type: application/octet-stream
          
